In [1]:
import numpy as np

In [2]:
x = np.array([[5,0,4,0,3,3],
            [0,4,0,0,3,0],
            [3,0,0,3,0,0],
            [0,4,0,5,0,1]])

In [3]:
R = np.asmatrix(x)
R

matrix([[5, 0, 4, 0, 3, 3],
        [0, 4, 0, 0, 3, 0],
        [3, 0, 0, 3, 0, 0],
        [0, 4, 0, 5, 0, 1]])

In [4]:
U,I = R.shape
f = 3

In [5]:
#p = np.random.rand(U,f)
#q = np.random.rand(f,I)
p = np.array([[0.11,0.07,0.19],
            [0.09,0.16,0.19],
            [0.09,0.05,0.04],
            [0.03,0.13,0.18]])
q = np.array([[0.16,0.01,0.07,0.17,0.02,0.20],
             [0.18,0.19,0.10,0.05,0.18,0.15],
             [0.02,0.18,0.03,0.14,0.17,0.06]])

In [6]:
P = np.asmatrix(p)
Q = np.asmatrix(q)

In [7]:
P

matrix([[0.11, 0.07, 0.19],
        [0.09, 0.16, 0.19],
        [0.09, 0.05, 0.04],
        [0.03, 0.13, 0.18]])

In [8]:
Q

matrix([[0.16, 0.01, 0.07, 0.17, 0.02, 0.2 ],
        [0.18, 0.19, 0.1 , 0.05, 0.18, 0.15],
        [0.02, 0.18, 0.03, 0.14, 0.17, 0.06]])

In [9]:
lambda_p = 0.06
lambda_q = 0.06

In [10]:
t = 1
max_training_round = 1

In [11]:
Ui = [2,2,1,2,2,2]
Iu = [4,2,2,3]

In [12]:
UserUp = np.zeros((U,f), dtype=float)
UserDown = np.zeros((U,f), dtype=float)
ItemUp = np.zeros((f,I), dtype=float)
ItemDown = np.zeros((f,I), dtype=float)

In [13]:
 for u in range(U):
        for i in range(I):
            if(R[u,i] != 0):
                rui_cap = P[u,:]*Q[:,i]
                for k in range(f):
                    UserUp[u,k] = UserUp[u,k] + Q[k,i] * R[u,i]
                    UserDown[u,k] = UserDown[u,k] + Q[k,i] * rui_cap
                    ItemUp[k,i] = ItemUp[k,i] + P[u,k] * R[u,i]
                    ItemDown[k,i] = ItemDown[k,i] + P[u,k]*rui_cap

In [14]:
UserUp

array([[1.74, 2.29, 0.91],
       [0.1 , 1.3 , 1.23],
       [0.99, 0.69, 0.48],
       [1.09, 1.16, 1.48]])

In [15]:
UserDown

array([[0.01659 , 0.023223, 0.011933],
       [0.001913, 0.023767, 0.022483],
       [0.00785 , 0.005526, 0.00376 ],
       [0.01409 , 0.018191, 0.017662]])

In [17]:
ItemUp

array([[0.82, 0.48, 0.44, 0.42, 0.6 , 0.36],
       [0.5 , 1.16, 0.28, 0.8 , 0.69, 0.34],
       [1.07, 1.48, 0.76, 1.02, 1.14, 0.75]])

In [18]:
ItemDown

array([[0.005918, 0.007617, 0.002244, 0.00321 , 0.010842, 0.005918],
       [0.00359 , 0.017942, 0.001428, 0.005954, 0.013361, 0.007792],
       [0.007428, 0.022777, 0.003876, 0.00756 , 0.0209  , 0.014875]])

In [19]:
for u in range(U):
        for k in range(f):
            UserDown[u,k] = UserDown[u,k] + Iu[u] * lambda_p * P[u,k]
            P[u,k] = P[u,k] * (UserUp[u,k]/UserDown[u,k])

In [20]:
UserDown

array([[0.04299 , 0.040023, 0.057533],
       [0.012713, 0.042967, 0.045283],
       [0.01865 , 0.011526, 0.00856 ],
       [0.01949 , 0.041591, 0.050062]])

In [21]:
P

matrix([[4.45219819, 4.00519701, 3.00523178],
        [0.70793676, 4.84092443, 5.16087715],
        [4.77747989, 2.99323269, 2.24299065],
        [1.67778348, 3.62578442, 5.32140146]])

In [22]:
for i in range(I):
        for k in range(f):
            ItemDown[k,i] = ItemDown[k,i] + Ui[i] * lambda_q * Q[k,i]
            Q[k,i] = Q[k,i] * (ItemUp[k,i]/ItemDown[k,i])

In [23]:
ItemDown

array([[0.025118, 0.008817, 0.006444, 0.02361 , 0.013242, 0.029918],
       [0.02519 , 0.040742, 0.007428, 0.011954, 0.034961, 0.025792],
       [0.009828, 0.044377, 0.005676, 0.02436 , 0.0413  , 0.022075]])

In [24]:
Q

matrix([[5.22334581, 0.54440286, 4.77963998, 3.02414231, 0.90620752,
         2.40657798],
        [3.57284637, 5.40965097, 3.76952073, 3.34616028, 3.55252996,
         1.97735732],
        [2.17745218, 6.00310972, 4.01691332, 5.86206897, 4.69249395,
         2.0385051 ]])